apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: proj-mysql
        image: shakti497/proj-mysql-image:latest
        ports:
        - containerPort: 3307
